#!/bin/bash
echo "Mapping the actual user that will be copied to the Docker Image"
echo "============================================================"
echo "HOST USERNAME: $USER   --->  CONTAINER USERNAME: dev        "
echo "HOST USER ID: $UID     --->  CONTAINER USER ID: $UID        "
echo "============================================================"
echo $UID >> docker/.userid
echo "Building image, this could take some time..."
docker build -t automata-reactjs docker/
rm docker/.userid
